---
- name: Create Sliver user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.user_setup
  vars:
    user_setup_default_users: [ "{{ sliver_user }}" ]

- name: Check if .bash_profile exists for sliver user
  ansible.builtin.stat:
    path: "/home/{{ sliver_user.username }}/.bash_profile"
  register: bash_profile_stat
  become: true
  become_user: sliver

- name: Ensure .bash_profile exists for sliver user
  ansible.builtin.file:
    path: "/home/{{ sliver_user.username }}/.bash_profile"
    state: touch
    owner: sliver
    group: sliver
    mode: '0644'
  become: true
  become_user: sliver
  when: not bash_profile_stat.stat.exists

- name: Install asdf and go
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_users: [ "{{ sliver_user }}" ]

- name: Install required packages for Sliver
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ sliver_common_install_packages }}"
    package_management_debian_specific_packages: "{{ sliver_debian_packages }}"
    package_management_redhat_specific_packages: "{{ sliver_el_packages }}"

- name: Configure Git to allow install_path as a safe directory
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ install_path }}"
  become: true

- name: Download and build Sliver
  ansible.builtin.git:
    repo: 'https://github.com/bishopfox/sliver.git'
    dest: "{{ install_path }}"
    version: master
  become: true

- name: Check current ownership of {{ install_path }}
  ansible.builtin.stat:
    path: "{{ install_path }}"
  register: sliver_stat
  become: true

- name: Change ownership of install_path if needed
  ansible.builtin.file:
    path: "{{ install_path }}"
    owner: "{{ sliver_user.username }}"
    group: "{{ sliver_user.usergroup }}"
    recurse: true
    state: directory
  become: true
  register: ownership_change
  when: sliver_stat.stat.pw_name != sliver_user.username or sliver_stat.stat.gr_name != sliver_user.usergroup

- name: Add install_path to $PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:{{ install_path }}"
    insertafter: EOF
    regexp: "^export PATH=.*:{{ install_path }}.*$"
  become: true

- name: Build Sliver with a custom PATH
  ansible.builtin.command:
    cmd: gmake
    chdir: "{{ install_path }}"
  environment:
    PATH: "/home/{{ sliver_user.username }}/.asdf/shims:{{ ansible_env.PATH }}"
  become: true
  become_user: sliver
  become_flags: -i
  register: gmake_result
  changed_when: "'Some specific output' in gmake_result.stdout"

- name: Unpack Sliver server
  ansible.builtin.command:
    cmd: "{{ install_path }}/sliver-server unpack --force"
  become: true
  become_user: sliver
  changed_when: false

- name: Generate operator configs for users
  ansible.builtin.shell:
    cmd: |
      {{ install_path }}/sliver-server operator --name {{ sliver_user.username }} \
      --lhost localhost --save "{{ install_path }}/sliver-client/configs"
      chown -R {{ sliver_user.username }}:"{{ sliver_user.usergroup }}" "{{ install_path }}/sliver-client"
  become: true
  args:
    executable: /bin/bash
  changed_when: "'configs saved' in result.stdout"
  register: result

- name: Include systemd tasks
  ansible.builtin.include_tasks: systemd.yml
  when: setup_systemd | bool
