---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yaml"

- name: Include OS-Specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yaml"

- name: Create sliver installer from template
  ansible.builtin.template:
    src: install-sliver.sh.j2
    dest: "{{ install_path }}"
    mode: 0755
  changed_when: false

- name: Run the sliver installer
  ansible.builtin.command: "{{ install_path }}"
  changed_when: false

- name: Remove the sliver installer
  ansible.builtin.file:
    path: "{{ install_path }}"
    state: absent
  changed_when: false
