---
- name: Download sliver installer
  ansible.builtin.get_url:
    url: "{{ install_script_url }}"
    dest: "{{ download_path }}"
    mode: 0755
    owner: root
    group: root
  changed_when: false

- name: Run the sliver installer
  ansible.builtin.command: "{{ download_path }}"
  changed_when: false

- name: Remove the sliver installer
  ansible.builtin.file:
    path: "{{ download_path }}"
    state: absent
  changed_when: false
