---
- name: Create Sliver user
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.user_setup
  vars:
    user_setup_default_users:
      - username: "sliver"
        usergroup: "sliver"
        sudo: true
        shell: "{{ sliver_default_shell }}"

- name: Install asdf and go
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.asdf
  vars:
    asdf_users:
      - username: "{{ sliver_default_user }}"
        usergroup: "{{ sliver_default_group }}"
        shell: "{{ sliver_default_shell }}"
        plugins:
          - name: golang
            version: '1.22.0'
            scope: "global"

- name: Install required packages for Sliver
  ansible.builtin.include_role:
    name: cowdogmoo.workstation.package_management
  vars:
    package_management_common_install_packages: "{{ sliver_common_install_packages }}"
    package_management_debian_specific_packages: "{{ sliver_debian_packages }}"
    package_management_redhat_specific_packages: "{{ sliver_el_packages }}"

- name: Configure Git to allow /opt/sliver as a safe directory
  community.general.git_config:
    name: safe.directory
    scope: global
    value: /opt/sliver
  become: true

- name: Download and build Sliver
  ansible.builtin.git:
    repo: 'https://github.com/bishopfox/sliver.git'
    dest: /opt/sliver
    version: master
  become: true

- name: Ensure .bash_profile exists for sliver user
  ansible.builtin.file:
    path: /home/sliver/.bash_profile
    state: file
    owner: sliver
    group: sliver
    mode: '0644'
  become: true
  become_user: sliver

- name: Check current ownership of /opt/sliver
  ansible.builtin.stat:
    path: /opt/sliver
  register: sliver_stat
  become: true

- name: Change ownership of /opt/sliver if needed
  ansible.builtin.file:
    path: /opt/sliver
    owner: "{{ sliver_default_user }}"
    group: "{{ sliver_default_group }}"
    recurse: true
    state: directory
  become: true
  register: ownership_change
  when: sliver_stat.stat.pw_name != sliver_default_user or sliver_stat.stat.gr_name != sliver_default_group

- name: Add /opt/sliver to $PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/opt/sliver'
    insertafter: EOF
    regexp: '^export PATH=.*:/opt/sliver.*$'
  become: true

- name: Build Sliver with a custom PATH
  ansible.builtin.command:
    cmd: gmake
    chdir: /opt/sliver
  environment:
    PATH: "/home/sliver/.asdf/shims:{{ ansible_env.PATH }}"
  become: true
  become_user: sliver
  become_flags: -i
  register: gmake_result
  changed_when: "'Some specific output' in gmake_result.stdout"

- name: Unpack Sliver server
  ansible.builtin.command:
    cmd: /opt/sliver/sliver-server unpack --force
  become: true
  become_user: sliver
  changed_when: false
