---
- name: Create sliver installer from template
  ansible.builtin.template:
    src: install-sliver.sh.j2
    dest: "{{ install_path }}"
    mode: 0755
  changed_when: false

- name: Run the sliver installer
  ansible.builtin.command: "{{ install_path }}"
  changed_when: false

- name: Remove the sliver installer
  ansible.builtin.file:
    path: "{{ install_path }}"
    state: absent
  changed_when: false
