---
- name: Converge
  hosts: all
  become: true
  vars:
    server_path: /root/sliver-server
    client_path: /usr/local/bin/sliver
    sliver_service_path: /etc/systemd/system/sliver.service
    sliver_client_config_path: /root/.sliver-client/configs

  roles:
    - role: l50.sliver

  post_tasks:
    - name: Test sliver server is installed
      ansible.builtin.stat:
        path: "{{ server_path }}"

    - name: Test sliver client is installed
      ansible.builtin.stat:
        path: "{{ client_path }}"

    - name: Test sliver service is installed
      ansible.builtin.stat:
        path: "{{ sliver_service_path }}"
      when: setup_systemd

    - name: Test sliver operator config path is present
      ansible.builtin.stat:
        path: "{{ sliver_client_config_path }}"
