---
name: Molecule Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  role_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install ansible molecule docker
          python3 -m pip install molecule-docker

      - name: Run Molecule Test
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
