---
name: Molecule Test
on:
  pull_request:
  push:

jobs:
  role_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade \
          ansible-core \
          docker \
          molecule \
          molecule-docker \
          "molecule-plugins[docker]"

      - name: Install galaxy dependencies
        run: |
          ansible-galaxy install -v -r requirements.yml
          ansible-galaxy collection install -v -r requirements.yml
          mkdir -p $HOME/.ansible/roles/l50
          ln -s $PWD $HOME/.ansible/roles/l50/sliver

      - name: Run Molecule Test
        run: molecule converge && molecule verify
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
