---
name: Molecule Test
on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: "l50.sliver"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
          - centos8
          - debian10
          - debian11

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "l50.sliver"

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Test role with molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
