---
name: Molecule Test
on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: "l50.sliver"

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "l50.sliver"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python3 -m pip install ansible molecule[docker] docker

      - name: Test role with molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ubuntu2204
